sudo: false
language: python
python:
- 3.5
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
script: true
  - nosetests --with-coverage --coverage report
after_script:
  - coveralls
after_success:
  - codecov
before_install:
- openssl aes-256-cbc -K $encrypted_17b768b9576a_key -iv $encrypted_17b768b9576a_iv
  -in config.py.enc -out config.py -d
